// THIS FILE IS AUTOGENERATED
#ifndef __STRINGS_INCLUDE__
#define __STRINGS_INCLUDE__

namespace lng
{
	enum LNG
	{
		LNG_CHNGPASS_CURRENT = 1, // Current password:
		LNG_CHNGPASS_ERROR_CURRENT = 2, // Current password is invalid.
		LNG_CHNGPASS_ERROR_MISMATCHED = 3, // New password and retyped password do not match.
		LNG_CHNGPASS_ERROR_NOT_CHANGED = 4, // New password and the current password must be different.
		LNG_CHNGPASS_ERROR_ONE_MISSING = 5, // Not all fields has been filled in.
		LNG_CHNGPASS_NEW = 6, // New password:
		LNG_CHNGPASS_RETYPE = 7, // Retype new password:
		LNG_CHNGPASS_TITLE = 8, // Password Change
		LNG_CHNGPASS_TITLE_FOR = 9, // Changing password for %1
		LNG_CMD_CLOSE = 10, // Close
		LNG_CMD_RESET = 11, // Reset
		LNG_CMD_SEND = 12, // Send
		LNG_CMD_UPDATE = 13, // Update
		LNG_GLOBAL_DESCRIPTION = 14, // stay up to date
		LNG_GLOBAL_PRODUCT = 15, // Aggregator
		LNG_GLOBAL_SITENAME = 16, // Aggregator
		LNG_LOGIN_ABSTRACT = 17, // Welcome to the Aggregator, your somsink, somsink.
		LNG_LOGIN_ERROR_MISMATCHED = 18, // Username and password do not match each other.
		LNG_LOGIN_ERROR_ONE_MISSING = 19, // Both username and password are required.
		LNG_LOGIN_FORGOT = 20, // I forgot my password
		LNG_LOGIN_PASSWORD = 21, // Password:
		LNG_LOGIN_STAY = 22, // Stay signed in
		LNG_LOGIN_TITLE = 23, // Login
		LNG_LOGIN_UI_STALE = 24, // Due to security reasons, you must sign in again
		LNG_LOGIN_USERNAME = 25, // Username:
		LNG_LOGIN_USERNAME_HINT = 26, // Use login or e-mail
		LNG_NAV_HELP = 27, // Help
		LNG_NAV_NEW_MENU = 28, // Subscribe
		LNG_NAV_NEW_MENU_TIP = 29, // Add New Feed
		LNG_NAV_REFRESH = 30, // Refresh
		LNG_NAV_SEARCH = 31, // Search
		LNG_NAV_SETTINGS = 32, // Settings
		LNG_NAV_SIGNIN = 33, // Sign In
		LNG_NAV_SIGNOUT = 34, // Sign Out
		LNG_NAV_SKIP = 35, // Skip to content
		LNG_RESET_TITLE = 36, // Reset my password
		LNG_RESET_USERNAME_HINT = 37, // Enter your user name or your e-mail
		LNG_USER_HELLO = 38, // Hello, %1!
		LNG_USER_SETTINGS_CHANGE_PASSWORD = 39, // Change password
		LNG_USER_SETTINGS_EMAIL = 40, // E-Mail:
		LNG_USER_SETTINGS_ERROR_EMAIL_ALREADY_USED = 41, // E-mail address used by different account.
		LNG_USER_SETTINGS_ERROR_EMAIL_FILLED = 42, // E-mail address must be filled out.
		LNG_USER_SETTINGS_ERROR_INVALID_PASSWORD = 43, // Current password is invalid.
		LNG_USER_SETTINGS_ERROR_NAME_REQUIRED = 44, // User name must be filled out.
		LNG_USER_SETTINGS_ERROR_SOME_ISSUES = 45, // There were some issues:
		LNG_USER_SETTINGS_NAME = 46, // Name:
		LNG_USER_SETTINGS_PASSWORD_MAIL_HINT = 47, // You must supply password if you want to change e-mail
		LNG_USER_SETTINGS_SEC_SIGNIN = 48, // Signing in
		LNG_USER_SETTINGS_TITLE = 49, // Settings
	};
} // lng
#endif // __STRINGS_INCLUDE__
