// THIS FILE IS AUTOGENERATED
#ifndef __STRINGS_INCLUDE__
#define __STRINGS_INCLUDE__

namespace lng
{
	enum LNG
	{
		CULTURE = 0, // ISO code for the culture
		LNG_CHNGPASS_CURRENT = 1, // Current password:
		LNG_CHNGPASS_ERROR_CURRENT = 2, // Current password is invalid.
		LNG_CHNGPASS_ERROR_MISMATCHED = 3, // New password and retyped password do not match.
		LNG_CHNGPASS_ERROR_NOT_CHANGED = 4, // New password and the current password must be different.
		LNG_CHNGPASS_ERROR_ONE_MISSING = 5, // Not all fields has been filled in.
		LNG_CHNGPASS_NEW = 6, // New password:
		LNG_CHNGPASS_RETYPE = 7, // Retype new password:
		LNG_CHNGPASS_TITLE = 8, // Password Change
		LNG_CHNGPASS_TITLE_FOR = 9, // Changing password for %1
		LNG_CMD_ADD = 10, // Add
		LNG_CMD_CLOSE = 11, // Close
		LNG_CMD_RESET = 12, // Reset
		LNG_CMD_SEND = 13, // Send
		LNG_CMD_UPDATE = 14, // Update
		LNG_FEED_ERROR = 15, // Unknown error occured while feed was downloaded
		LNG_FEED_FAILED = 16, // Feed could not be found
		LNG_FEED_MISSING = 17, // Feed parameter is missing
		LNG_FEED_SERVER_FAILED = 18, // Feed server did not respond
		LNG_FEED_UNKNOWN = 19, // Feed is unknown
		LNG_GENERIC_LIST_LAST = 20, // and
		LNG_GLOBAL_DESCRIPTION = 21, // stay up to date
		LNG_GLOBAL_PRODUCT = 22, // reedr
		LNG_GLOBAL_SITENAME = 23, // reedr
		LNG_LOGIN_ABSTRACT = 24, // Welcome to the reedr, your somsink, somsink.
		LNG_LOGIN_ERROR_MISMATCHED = 25, // Username and password do not match each other.
		LNG_LOGIN_ERROR_ONE_MISSING = 26, // Both username and password are required.
		LNG_LOGIN_FORGOT = 27, // I forgot my password
		LNG_LOGIN_PASSWORD = 28, // Password:
		LNG_LOGIN_STAY = 29, // Stay signed in
		LNG_LOGIN_TITLE = 30, // Login
		LNG_LOGIN_UI_STALE = 31, // Due to security reasons, you must sign in again
		LNG_LOGIN_USERNAME = 32, // Username:
		LNG_LOGIN_USERNAME_HINT = 33, // Use login or e-mail
		LNG_NAV_HELP = 34, // Help
		LNG_NAV_NEW_MENU = 35, // Subscribe
		LNG_NAV_NEW_MENU_TIP = 36, // Add New Feed
		LNG_NAV_REFRESH = 37, // Refresh
		LNG_NAV_SEARCH = 38, // Search
		LNG_NAV_SETTINGS = 39, // Settings
		LNG_NAV_SIGNIN = 40, // Sign In
		LNG_NAV_SIGNOUT = 41, // Sign Out
		LNG_NAV_SKIP = 42, // Skip to content
		LNG_NOT_A_FEED = 43, // URL does not point to a known feed format
		LNG_RESET_TITLE = 44, // Reset my password
		LNG_RESET_USERNAME_HINT = 45, // Enter your user name or your e-mail
		LNG_SUBSCRIBE_ERROR = 46, // There was a communication error with the server. Please try again later.
		LNG_SUBSCRIBE_HINT = 47, // eg. http://xkcd.com/atom.xml
		LNG_SUBSCRIBE_PROMPT = 48, // Enter feed URL
		LNG_URL_MISSING = 49, // URL parameter is missing
		LNG_USER_HELLO = 50, // Hello, %1!
		LNG_USER_SETTINGS_CHANGE_PASSWORD = 51, // Change password
		LNG_USER_SETTINGS_EMAIL = 52, // E-Mail:
		LNG_USER_SETTINGS_ERROR_EMAIL_ALREADY_USED = 53, // E-mail address used by different account.
		LNG_USER_SETTINGS_ERROR_EMAIL_FILLED = 54, // E-mail address must be filled out.
		LNG_USER_SETTINGS_ERROR_INVALID_PASSWORD = 55, // Current password is invalid.
		LNG_USER_SETTINGS_ERROR_NAME_REQUIRED = 56, // User name must be filled out.
		LNG_USER_SETTINGS_ERROR_SOME_ISSUES = 57, // There were some issues:
		LNG_USER_SETTINGS_NAME = 58, // Name:
		LNG_USER_SETTINGS_PASSWORD_MAIL_HINT = 59, // You must supply password if you want to change e-mail
		LNG_USER_SETTINGS_SEC_SIGNIN = 60, // Signing in
		LNG_USER_SETTINGS_TITLE = 61, // Settings
		LNG_VIEW_ALL_ITEMS = 62, // All items
		LNG_VIEW_BY = 63, // by 
		LNG_VIEW_ENCLOSURE = 64, // Attachment:
		LNG_VIEW_ENCLOSURES = 65, // Attachments:
		LNG_VIEW_HOME = 66, // Home
		LNG_VIEW_PUBLISHED_UNDER = 67, // published under:
		LNG_VIEW_SUBSCRIPTIONS = 68, // Subscriptions
		LNG_VIEW_TITLE_MISSING = 69, // (no title)
	};
} // lng
#endif // __STRINGS_INCLUDE__
