// THIS FILE IS AUTOGENERATED
#ifndef __STRINGS_INCLUDE__
#define __STRINGS_INCLUDE__

namespace lng
{
	enum LNG
	{
		LNG_CHNGPASS_CURRENT = 1, // Current password:
		LNG_CHNGPASS_ERROR_CURRENT = 2, // Current password is invalid.
		LNG_CHNGPASS_ERROR_MISMATCHED = 3, // New password and retyped password do not match.
		LNG_CHNGPASS_ERROR_NOT_CHANGED = 4, // New password and the current password must be different.
		LNG_CHNGPASS_ERROR_ONE_MISSING = 5, // Not all fields has been filled in.
		LNG_CHNGPASS_NEW = 6, // New password:
		LNG_CHNGPASS_RETYPE = 7, // Retype new password:
		LNG_CHNGPASS_TITLE = 8, // Password Change
		LNG_CHNGPASS_TITLE_FOR = 9, // Changing password for %1
		LNG_CMD_CLOSE = 10, // Close
		LNG_CMD_RESET = 11, // Reset
		LNG_CMD_SEND = 12, // Send
		LNG_CMD_UPDATE = 13, // Update
		LNG_FEED_ERROR = 14, // Unknown error occured while feed was downloaded
		LNG_FEED_FAILED = 15, // Feed could not be found
		LNG_FEED_SERVER_FAILED = 16, // Feed server did not respond
		LNG_GLOBAL_DESCRIPTION = 17, // stay up to date
		LNG_GLOBAL_PRODUCT = 18, // reedr
		LNG_GLOBAL_SITENAME = 19, // reedr
		LNG_LOGIN_ABSTRACT = 20, // Welcome to the reedr, your somsink, somsink.
		LNG_LOGIN_ERROR_MISMATCHED = 21, // Username and password do not match each other.
		LNG_LOGIN_ERROR_ONE_MISSING = 22, // Both username and password are required.
		LNG_LOGIN_FORGOT = 23, // I forgot my password
		LNG_LOGIN_PASSWORD = 24, // Password:
		LNG_LOGIN_STAY = 25, // Stay signed in
		LNG_LOGIN_TITLE = 26, // Login
		LNG_LOGIN_UI_STALE = 27, // Due to security reasons, you must sign in again
		LNG_LOGIN_USERNAME = 28, // Username:
		LNG_LOGIN_USERNAME_HINT = 29, // Use login or e-mail
		LNG_NAV_HELP = 30, // Help
		LNG_NAV_NEW_MENU = 31, // Subscribe
		LNG_NAV_NEW_MENU_TIP = 32, // Add New Feed
		LNG_NAV_REFRESH = 33, // Refresh
		LNG_NAV_SEARCH = 34, // Search
		LNG_NAV_SETTINGS = 35, // Settings
		LNG_NAV_SIGNIN = 36, // Sign In
		LNG_NAV_SIGNOUT = 37, // Sign Out
		LNG_NAV_SKIP = 38, // Skip to content
		LNG_NOT_A_FEED = 39, // URL does not point to a known feed format
		LNG_RESET_TITLE = 40, // Reset my password
		LNG_RESET_USERNAME_HINT = 41, // Enter your user name or your e-mail
		LNG_URL_MISSING = 42, // URL parameter is missing
		LNG_USER_HELLO = 43, // Hello, %1!
		LNG_USER_SETTINGS_CHANGE_PASSWORD = 44, // Change password
		LNG_USER_SETTINGS_EMAIL = 45, // E-Mail:
		LNG_USER_SETTINGS_ERROR_EMAIL_ALREADY_USED = 46, // E-mail address used by different account.
		LNG_USER_SETTINGS_ERROR_EMAIL_FILLED = 47, // E-mail address must be filled out.
		LNG_USER_SETTINGS_ERROR_INVALID_PASSWORD = 48, // Current password is invalid.
		LNG_USER_SETTINGS_ERROR_NAME_REQUIRED = 49, // User name must be filled out.
		LNG_USER_SETTINGS_ERROR_SOME_ISSUES = 50, // There were some issues:
		LNG_USER_SETTINGS_NAME = 51, // Name:
		LNG_USER_SETTINGS_PASSWORD_MAIL_HINT = 52, // You must supply password if you want to change e-mail
		LNG_USER_SETTINGS_SEC_SIGNIN = 53, // Signing in
		LNG_USER_SETTINGS_TITLE = 54, // Settings
	};
} // lng
#endif // __STRINGS_INCLUDE__
